Repository eldolar/web, pull requests merged in 2020-10, with the labels that each got.

#16 Update README.md
  README.md
Labels: hacktoberfest-accepted

#7 Add simple contributing guideline
  CONTRIBUTING.MD
Labels: Hacktoberfest

#9 Remove twitter icon from footer
  src/components/Footer.js
Labels: Hacktoberfest

#19 Create the home banking links and a new style for name
  src/components/Bank.js
  src/styles/Bank.module.scss
Labels: Hacktoberfest, hacktoberfest-accepted

#10 Swap the price columns
  src/components/Bank.js
Labels: Hacktoberfest, hacktoberfest-accepted
